/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});
export const OrderCallback = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Text,
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'bookTable' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getOrderCallbacks' : IDL.Func([], [IDL.Vec(OrderCallback)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'requestOrderCallback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  const OrderCallback = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Text,
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'bookTable' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getOrderCallbacks' : IDL.Func([], [IDL.Vec(OrderCallback)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'requestOrderCallback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };